version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000" # Используем 8001, чтобы не конфликтовать с FastAPI
    volumes:
      - chroma_data:/chroma
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
      - chromadb
      - redis
    restart: unless-stopped

  telegram_bot:
    build:
      context: ./telegram_bot
    container_name: telegram_bot_service
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
  
  analytics:
    build:
      context: ./analytics
    container_name: analytics_dashboard
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data:
  ollama_data: 