version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  anythingllm:
    image: anythingllm/anythingllm:latest
    container_name: anythingllm
    ports:
      - "3001:3001" # Веб-интерфейс AnythingLLM
    volumes:
      - anythingllm_storage:/app/server/storage
      - anythingllm_hotdir:/app/collector/hotdir # Папка для авто-загрузки документов
    depends_on:
      - ollama
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN # Требуется для Puppeteer внутри контейнера

  backend:
    build:
      context: ./backend
    container_name: backend_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - anythingllm
    restart: unless-stopped

  telegram_bot:
    build:
      context: ./telegram_bot
    container_name: telegram_bot_service
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./telegram_bot/logs:/app/logs
    restart: unless-stopped
  
  analytics:
    build:
      context: ./analytics
    container_name: analytics_dashboard
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./telegram_bot/logs:/app/telegram_bot/logs:ro # Только чтение
    restart: unless-stopped

volumes:
  ollama_data:
  anythingllm_storage:
  anythingllm_hotdir: 